language: php

php:
  - 7.1

services:
  - mysql

# Only watch the master branch and tagged release.
branches:
 only:
   - master
   - develop
   - stage
   - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_script:
  - mysql -u root -e 'CREATE DATABASE homestead_test;'
    mysql -u root -e "CREATE USER 'homestead'@'localhost' IDENTIFIED BY
    'secret';"
  - mysql -u root -e "GRANT ALL ON homestead_test.* TO 'homestead'@'localhost';"
  - cp .env.travis .env
  - composer self-update
  - composer clear-cache -vvv
  - composer install --no-interaction -vvv
  - composer dump-autoload -vvv
  - php artisan migrate:refresh --seed
  - npm install newman

script:
  - 'nohup php -S 0.0.0.0:8000 -t public public/index.php > /dev/null 2>&1 &'
  - node_modules/.bin/newman run tests/postman/practice.json -e tests/postman/practice-env-local.json
  - ./vendor/bin/phpunit
